In [1]:
!pip install gymnasium

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 953.9/953.9 kB 16.8 MB/s eta 0:00:00


In [2]:
import numpy as np #scientific calculation or to deal with arrays
import gymnasium as gym #provides you with the environment

In [3]:
env=gym.make("CliffWalking")

/usr/local/lib/python3.10/dist-packages/gymnasium/envs/registration.py:521: UserWarning: WARN: Using the latest versioned environment `CliffWalking-v0` instead of the unversioned environment `CliffWalking`.
  logger.warn(


In [4]:
env=gym.make("CliffWalking",render_mode='rgb_array')#rgb_array for recording video
n_observation = env.observation_space.n
n_action = env.action_space.n

In [5]:
print('number of states',n_observation)
print('number of possible actions',n_action)

number of states 48
number of possible actions 4


In [6]:
#Initialize the Q-table to 0
Q_table = np.zeros((n_observation,n_action))
print(Q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
Q_table.shape #48 states with 4 actions each

(48, 4)

In [8]:
#number of episode we will run
n_episodes = 10000

#maximum of iteration per episode- Or number of steps per episode
steps_allowed = 500

#initialize the exploration probability to 1
epsilon = 1

#exploartion decreasing decay for exponential decreasing
decay_rate = 0.001

# minimum of exploration proba
min_epsilon = 0.01

#max exploration rate
max_epsilon=1

#discounted factor- Return G(t)- continuos task
gamma = 0.97

#learning rate - Alpha - Update Q values- storing new info as well as preserving the old one
lr = 0.1

In [9]:
#Storing rewards after each episode in a list
rewards_per_episode = list()



**Training**


In [10]:
#Greedy Policy
def choose_action(state):
    action=0
    if np.random.uniform(0, 1) < epsilon:
        action = env.action_space.sample()
    else:
        action = np.argmax(Q_table[state, :])
    return action

In [11]:
#we iterate over episodes
for e in range(n_episodes): #Entering in the episode
  #we initialize the first state of the episode
  state = env.reset()[0]
  done = False
  action1=choose_action(state)
  #sum the rewards that the agent gets from the environment
  total_reward = 0

  for i in range(steps_allowed): #individual steps taken within an episode
    # epsilon greedy strategy
    # we initiate a random number between 0 and 1
    # if the random_number is less than the exploration proba(epsilon)
    #     the agent explores
    # else
    #     he exploits his knowledge



    # The environment runs the chosen action and returns
    # the next state, a reward and true if the episode is ended.
    next_state, reward, done, truncated , info = env.step(action1)
    action2=choose_action(next_state)

    # We update our Q-table using the Q-learning iteration
    Q_table[state, action1] = (1-lr) * Q_table[state, action1]+ lr*(reward + gamma*(Q_table[next_state,action2]))
    total_reward = total_reward + reward

    state = next_state
    action1=action2
    # If the episode is finished, we leave the for loop
    if done:
        break

  #We update the exploration proba using exponential decay formula
  epsilon = min_epsilon + (max_epsilon - min_epsilon) * np.exp(-decay_rate*e)
  rewards_per_episode.append(total_reward)

In [12]:
len(rewards_per_episode)

10000

In [13]:
rewards_per_thousand_episodes=np.split(np.array(rewards_per_episode),50)

In [14]:
count=1000
print('-----Average reward per thousand episodes-------')
for r in rewards_per_thousand_episodes:
  print(count,':' ,str(sum(r/1000)))
  count+=1000

-----Average reward per thousand episodes-------
1000 : -601.9190000000001
2000 : -206.47799999999992
3000 : -166.32599999999974
4000 : -129.8969999999999
5000 : -110.65299999999998
6000 : -108.41499999999996
7000 : -103.86099999999999
8000 : -102.17800000000003
9000 : -102.57400000000003
10000 : -100.594
11000 : -101.08899999999998
12000 : -100.594
13000 : -100.99
14000 : -100.693
15000 : -100.69300000000001
16000 : -100.49499999999999
17000 : -100.099
18000 : -100.396
19000 : -100.198
20000 : -100.19800000000001
21000 : -100.0
22000 : -100.09899999999999
23000 : -100.099
24000 : -100.0
25000 : -100.19800000000001
26000 : -100.09899999999999
27000 : -100.297
28000 : -100.0
29000 : -100.19800000000001
30000 : -100.099
31000 : -100.0
32000 : -100.0
33000 : -100.099
34000 : -100.099
35000 : -100.099
36000 : -100.0
37000 : -100.0
38000 : -100.099
39000 : -100.0
40000 : -100.099
41000 : -100.099
42000 : -100.0
43000 : -100.0
44000 : -100.09899999999999
45000 : -100.099
46000 : -100.0
47000

In [15]:
print('-----------Updated Q Table-----------')
print(Q_table)

-----------Updated Q Table-----------
[[ -33.33333363  -33.33334526  -33.33333711  -33.33333576]
 [ -33.33362947  -33.33507053  -33.33990256  -33.3333384 ]
 [ -33.36967205  -33.47526355  -33.78348721  -33.33337734]
 [ -35.66328948  -38.73349657  -35.4382335   -33.36696824]
 [ -50.48432788  -66.52415424  -62.95020199  -35.33538778]
 [ -81.29344069  -77.96016557  -95.28860543  -48.63693664]
 [ -89.52411558  -71.66130054 -107.7030087   -86.84331704]
 [ -80.19145252  -63.32717532  -97.64056634  -87.06596008]
 [ -73.38706513  -57.32646943  -76.77599538  -79.22091399]
 [ -60.6366295   -49.59075403  -72.08245195  -72.82759779]
 [ -52.96271139  -47.48211829  -54.1971056   -59.60143519]
 [ -49.05500397  -48.95243816  -46.38892589  -50.78285017]
 [ -33.3333351   -33.33349545  -33.34376397  -33.33394714]
 [ -33.33337436  -34.53541081  -33.50631164  -33.37062038]
 [ -33.38340193  -42.2602479   -52.56489745  -34.07828308]
 [ -34.155365    -57.83962677  -69.0061508   -37.61712625]
 [ -42.35436034  -

In [16]:
import time
from IPython.display import clear_output

In [23]:
#For recording video
%pip install gymnasium[classic_control] comet_ml
import comet_ml
comet_ml.init(project_name="cliff_walking_q_learning")
env = gym.wrappers.RecordVideo(env, 'gameplay video') #fdiox3CS3j2WHY7yzjJclVgbt

COMET WARNING: comet_ml.init() is deprecated and will be removed soon. Please use comet_ml.login()
/usr/local/lib/python3.10/dist-packages/gymnasium/wrappers/record_video.py:94: UserWarning: WARN: Overwriting existing videos at /content/gameplay video folder (try specifying a different `video_folder` for the `RecordVideo` wrapper if this is not desired)
  logger.warn(


In [ ]:
#Visualising the game
for episode in range(3):
  state=env.reset()[0]
  done=False
  print('----------EPISODE:',episode+1,'---------\n\n\n\n')
  time.sleep(1)

  for step in range(steps_allowed):
    clear_output(wait=True)
    print(env.render())
    time.sleep(0.3)

    action = np.argmax(Q_table[state,:])
    new_state, reward, done, truncated, info = env.step(action)

    if done:
      clear_output(wait=True)
      print(env.render())
      if reward == -100:
          print("****You fell off the cliff****")
          time.sleep(3)
      else:
          print("****You reached the goal****")
          time.sleep(3)
      clear_output(wait=True)
      break

    state=new_state

env.close()

[[[ 91 150  97]
  [ 91 150  97]
  [ 91 150  97]
  ...
  [ 86 170  69]
  [ 86 170  69]
  [ 86 170  69]]

 [[ 91 150  97]
  [ 91 150  97]
  [ 91 150  97]
  ...
  [ 86 170  69]
  [ 86 170  69]
  [ 86 170  69]]

 [[ 91 150  97]
  [ 91 150  97]
  [ 98 166 105]
  ...
  [105 182  74]
  [105 182  74]
  [ 86 170  69]]

 ...

 [[ 86 170  69]
  [ 86 170  69]
  [ 93 188  74]
  ...
  [ 91 150  97]
  [ 91 150  97]
  [ 91 150  97]]

 [[ 86 170  69]
  [ 86 170  69]
  [ 93 188  74]
  ...
  [ 91 150  97]
  [ 91 150  97]
  [ 91 150  97]]

 [[ 86 170  69]
  [ 86 170  69]
  [ 86 170  69]
  ...
  [ 91 150  97]
  [ 91 150  97]
  [ 91 150  97]]]
